### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by drakoevil** [NachoBrito/QuipuForJoomla#1]
Nacho tu tienes una version mas actualizada no funciona bien con las ultimas versiones de joomla pero me parece una aplicación genial

**Comment by NachoBrito** [comment]
Hola!,

Lo siento, aún no he tenido tiempo de adaptar Quipu a las últimas 
versiones de Joomla. Intentaré hacerlo en breve, aunque no puedo 
comprometer una fecha...

Saludos,

El 29/3/15 a las 18:53, drakoevil escribió:
>
> Nacho tu tienes una version mas actualizada no funciona bien con las 
> ultimas versiones de joomla pero me parece una aplicación genial
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NachoBrito/QuipuForJoomla/issues/1>.
>

-- 
Nacho Brito.

**Comment by N6REJ** [comment]
does it do automatic monthly billing?
and paypal payments?

**Comment by NachoBrito** [comment]
Sorry, none of those. There is no integration payment, but the extension 
can recognize payments in bank account movements if the invoice number 
is present and create the association.

El 31/5/15 a las 8:08, Bear escribió:
>
> does it do automatic monthly billing?
> and paypal payments?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NachoBrito/QuipuForJoomla/issues/1#issuecomment-107131795>.
>

-- 
Nacho Brito.

**Comment by Diegopintos** [comment]
Hi I just installed the extension and when I want to create an order telling me this error.
Is there a solution? Why ? 

1062 Duplicate entry 'order-2' for key 'name' SQL=UPDATE glgrb_quipu_sequence SET next_value='2' WHERE name='order';

Congratulations is a great extension
Might you help me?

**Comment by NachoBrito** [comment]
Try changing your "next order number" value in config (/index.php?option=com_quipu&view=config&layout=edit&id=1) . Set a value bigger than 2.

**Comment by Diegopintos** [comment]
Forgive but I try to change the value of the configuration fields but still has problems. And the result is always the same with these values.

I have also tried to name the fields with letters and numbers. what happens then is that it keeps causing problems with the picture, and when I try to create an order says the same mistake in duplicate.

Next invoice number * 1  
Next number Abono * 0 
Next Order No. *1 
No. next purchase * 1
Currency symbol € 

is my first experience in this type of extensions I'm sure it's silly.

maybe you prefer to continue this thread in private? my english is not too good.? jur jur jur... .. .

**Comment by NachoBrito** [comment]
;-)

Tienes acceso al contenido de la base de datos? puedes decirme qué hay en la tabla glgrb_quipu_sequence?

**Comment by Diegopintos** [comment]
Si tengo, no se realmente que es lo que quieres y te he pegado lo que podido la próxima tiro de captura.

id	              int(10)		UNSIGNED                    AUTO_INCREMENT
name	      char(20)	        utf8_general_ci	
next_value     int(10)		UNSIGNED

Examine
1 invoice 0
7 invoice 1
2 order   0
5 order 1
3 purchaseorder 0
6 purchaseorder 1
4 refund 0

**Comment by NachoBrito** [comment]
Sobran los duplicados. Borra las filas con  id 1,2,3 y 4
Nacho.
El 15/8/2015 12:55 p. m., Liontv <notifications@github.com> escribió:Si tengo, no se realmente que es lo que quieres y te he pegado lo que podido la próxima tiro de captura.

id                int(10)       UNSIGNED                    AUTO_INCREMENT
name          char(20)          utf8_general_ci 
next_value     int(10)      UNSIGNED

Examine
1 invoice 0
7 invoice 1
2 order   0
5 order 1
3 purchaseorder 0
6 purchaseorder 1
4 refund 0

**Comment by Diegopintos** [comment]
ooo Perfecto funciona... muchas muchas gracias Nacho tu extensión es un recurso perfecto para gestionar pequeños colectivos y asociaciones seguiré trabajando para presentarsela a la directiva de una reciente asociación en la que estoy de tesorero.
Un saludo y muchas gracias.

**Comment by NachoBrito** [comment]
Genial, me alegro mucho :-)
Nacho.
El 15/8/2015 1:18 p. m., Liontv <notifications@github.com> escribió:ooo Perfecto funciona... muchas muchas gracias Nacho tu extensión es un recurso perfecto para gestionar pequeños colectivos y asociaciones seguiré trabajando para presentarsela a la directiva de una reciente asociación en la que estoy de tesorero.
Un saludo y muchas gracias.

**Comment by nunomig** [comment]
Hello,

i just installed QUIPU but it gives me an error when saving an order
"Warning: Failed to move file!
Could not save purchase order because an error happened when saving the invoice file"

Can you help me?

Best Regards
